# Generated by Django 5.0.2 on 2024-02-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Буква')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Англйиский алфавит',
                'verbose_name_plural': 'Английский алфавит',
            },
        ),
        migrations.CreateModel(
            name='KazakhAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Буква')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Казахский алфавит',
                'verbose_name_plural': 'Казахский алфавит',
            },
        ),
        migrations.CreateModel(
            name='RussianAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Буква')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Русский алфавит',
                'verbose_name_plural': 'Русский алфавит',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название темы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='WorkingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название класса')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='WordInEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=90, verbose_name='Название слова')),
                ('transcript', models.CharField(blank=True, max_length=160, null=True, verbose_name='Транскрипт (необязательное поле)')),
                ('subword', models.CharField(max_length=160, verbose_name='Дополнительно')),
                ('description', models.TextField(verbose_name='Описание')),
                ('voice', models.FileField(upload_to='voices/en/', verbose_name='Произношение')),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.russianalphabet', verbose_name='Буква на русском')),
            ],
            options={
                'verbose_name': 'Слово на английском',
                'verbose_name_plural': 'Слова на английском',
            },
        ),
        migrations.CreateModel(
            name='WordInKz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=90, verbose_name='Название слова')),
                ('subword', models.CharField(max_length=160, verbose_name='Дополнительно')),
                ('description', models.TextField(verbose_name='Описание')),
                ('voice', models.FileField(upload_to='voices/kz/', verbose_name='Произношение')),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.kazakhalphabet', verbose_name='Буква на казахском')),
            ],
            options={
                'verbose_name': 'Слово на казахском',
                'verbose_name_plural': 'Слова на казахском',
            },
        ),
        migrations.CreateModel(
            name='WordInRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=90, verbose_name='Название слова')),
                ('subword', models.CharField(max_length=160, verbose_name='Дополнительно')),
                ('description', models.TextField(verbose_name='Описание')),
                ('voice', models.FileField(upload_to='voices/ru/', verbose_name='Произношение')),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.russianalphabet', verbose_name='Буква на русском')),
            ],
            options={
                'verbose_name': 'Слово на русском',
                'verbose_name_plural': 'Слова на русском',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='words/', verbose_name='Изображение')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.theme', verbose_name='Тема')),
                ('word_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.wordinen', verbose_name='Слово на английском')),
                ('word_kz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.wordinkz', verbose_name='Слово на казахском')),
                ('word_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.wordinru', verbose_name='Слово на русском')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
