# Generated by Django 5.0.2 on 2024-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilingo_app', '0003_theme_word_en_alter_theme_word_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishalphabet',
            name='image',
            field=models.ImageField(default='', upload_to='alphabet/kz/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='kazakhalphabet',
            name='image',
            field=models.ImageField(default='', upload_to='alphabet/kz/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='russianalphabet',
            name='image',
            field=models.ImageField(default='', upload_to='alphabet/kz/', verbose_name='Изображение'),
        ),
    ]
