# Generated by Django 5.0.2 on 2024-02-23 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilingo_app', '0004_englishalphabet_image_kazakhalphabet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='working_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.workingclass', verbose_name='Выберите класс'),
        ),
    ]
