# Generated by Django 5.0.2 on 2024-02-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilingo_app', '0005_theme_working_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinen',
            name='alphabet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilingo_app.englishalphabet', verbose_name='Буква на английском'),
        ),
    ]
